image: Visual Studio 2017

cache:
  - '%LocalAppData%\Microsoft\dotnet -> appveyor.yml'
  - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages -> appveyor.yml'

version: 0.0.1.{build}
skip_tags: true
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  NugetApiKey:
    secure: 3sC7bUSY534F4WnpYXlP7XyikulxbSpfLZgC3y37gA2OAeMp35la0zplVjiliOFn
  access_token:
    secure: eBkkiWtTuwTfnTN2G4n0RegBV+MImV3BoKYm2pGmi/0Lu3VGb4m07m5FJWq+29sD
  ModuleName: PSCoreWindowsCompat

skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

test_script:
- ps: . .\build.ps1
